swagger: "2.0"

info:
  version: "0.0.1"
  title: Ascent Diagramer REST API

produces:
  - image/png
  - application/json

paths:
  /health:
    get:
      operationId: get
      description: Get health status of
      responses:
        200:
          description: "Health check response"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
          examples:
            application/json: { "status": "UP"}
  /diagram:
    get:
      operationId: get
      description: Get diagram from BOM definition
      responses:
        200:
          description: "Diagram Image"
          schema:
            type: "file"
          content:
            image/png:
              schema:
                type: string
                format: binary
